In [35]:
%load_ext autoreload
# %autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [36]:
%autoreload 2
from src import matriz_aumentada, gauss_jordan

A = [
    [1, 2, 3, 4],
    [2, 5, 6, 7],
    [3, 6, 8, 9],
    [4, 7, 9, 10],
]
b = [1, -2, 3, 4]

Ab = matriz_aumentada(A, b) # type: ignore
gauss_jordan(Ab)

[01-29 12:54:17][INFO][lindm] 
[[ 1.  2.  3.  4.  1.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0. -1. -3. -6.  0.]]
[01-29 12:54:17][INFO][lindm] 
[[ 1.  0.  3.  6.  9.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0. -3. -7. -4.]]
[01-29 12:54:17][INFO][lindm] 
[[ 1.  0.  0. -3.  9.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0.  0.  2. -4.]]
[01-29 12:54:17][INFO][lindm] 
[[ 1.  0.  0.  0.  3.]
 [ 0.  1.  0.  0. -6.]
 [ 0.  0. -1.  0. -6.]
 [ 0.  0.  0.  2. -4.]]


array([ 3., -6.,  6., -2.])

# Resolver

In [37]:
import logging
from sys import stdout
from datetime import datetime
import os

logging.basicConfig(
    level=logging.INFO,
    format=f"[%(asctime)s][%(levelname)s][{os.environ.get('USERNAME')}] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)
logging.info(datetime.now())

[01-29 12:54:17][INFO][lindm] 2026-01-29 12:54:17.354653


In [38]:
import numpy as np
 ####################################################################
def inv_matrix(A: np.ndarray) -> np.ndarray:
    """Inversión de una matriz cuadrada mediante método de Gauss-Jordan.
    ## Parameters
    ``A``: matriz cuadrada de tamaño n x n.

    ## Return
    ``A_inv``: matriz inversa de A.
    """
    if not isinstance(A, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        A = np.array(
            A, dtype=float
        )  # convertir en float, porque si no, convierte en enteros
    #assert A.shape[0] == A.shape[1] - 1, "La matriz A debe ser de tamaño n-by-(n+1)."
    n = A.shape[0]

    for i in range(0, n):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if A[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            logging.info(f"\n{A}")
            raise ValueError("No existe solución única.")

        if p != i:
            logging.info(f"Intercambiando filas {i} y {p}.")
            # swap rows
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux

        # --- Eliminación: loop por fila
        for j in range(n):
            #if i == j:
            if j == i:
                continue
            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]

            A[i,:] = A[i,:] / A[i,i]  # Normalizar pivote a 1

        logging.info(f"\n{A}")

    if A[n - 1, n - 1] == 0:
        # Sin embargo, esto solo se accede al finalizar la matriz... Con todos los pivotes
        if A[n - 1, n] == 0:
            raise ValueError("Infinitas soluciones.")
        else:
            raise ValueError("Sin solución.")
        print(f'\n{A}')
        
    # --- Sustitución hacia atrás
    #solucion = np.zeros(n)
    #for i in range(n):
       # solucion[i] = A[i, n] / A[i, i]

    return A
    #pass

## Ejemplos
* Ejemplo 1

In [ ]:
# La matriz A =
A = [
    [1, 2, 3, 4],
    [2, 5, 6, 7],
    [3, 6, 8, 9],
    [4, 7, 9, 10],
]
# tiene como inversa
# A_inv =[[ 0.5, -0.5, -1.5,  1.5],
#        [-0.5,  1.5, -1.5,  0.5],
#        [-1.5, -1.5,  3.5, -1.5],
#        [ 1.5,  0.5, -1.5,  0.5]]

inv_matrix(A)


[01-29 12:55:03][INFO][lindm] 
[[ 1.  2.  3.  4.]
 [ 0.  1.  0. -1.]
 [ 0.  0. -1. -3.]
 [ 0. -1. -3. -6.]]
[01-29 12:55:03][INFO][lindm] 
[[ 1.  0.  3.  6.]
 [ 0.  1.  0. -1.]
 [ 0.  0. -1. -3.]
 [ 0.  0. -3. -7.]]
[01-29 12:55:03][INFO][lindm] 
[[ 1.  0.  0. -3.]
 [ 0.  1.  0. -1.]
 [-0. -0.  1.  3.]
 [ 0.  0.  0.  2.]]


[01-29 12:55:03][INFO][lindm] 
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [-0. -0.  1.  0.]
 [ 0.  0.  0.  1.]]


array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [-0., -0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

* Ejemplo 2

In [ ]:
# La matriz A =
A = [
    [4, 4, 5, 1],
    [3, 4, 2, 2],
    [2, 1, 4, 1],
    [3, 2, 5, 4],
]
# tiene como inversa
# A_inv =[[-34.,  31.,  52., -20.],
#         [ 19., -17., -29.,  11.],
#         [ 12., -11., -18.,   7.],
#         [  1.,  -1.,  -2.,   1.]]
inv_matrix(A)


[01-29 12:54:17][INFO][lindm] Intercambiando filas 0 y 2.
[01-29 12:54:17][INFO][lindm] 
[[ 1.   0.5  2.   0.5]
 [ 0.   2.5 -4.   0.5]
 [ 0.   2.  -3.  -1. ]
 [ 0.   0.5 -1.   2.5]]
[01-29 12:54:17][INFO][lindm] Intercambiando filas 1 y 3.


[01-29 12:54:17][INFO][lindm] 
[[  1.   0.   3.  -2.]
 [  0.   1.  -2.   5.]
 [  0.   0.   1. -11.]
 [  0.   0.   1. -12.]]
[01-29 12:54:17][INFO][lindm] 
[[  1.   0.   0.  31.]
 [  0.   1.   0. -17.]
 [  0.   0.   1. -11.]
 [  0.   0.   0.  -1.]]
[01-29 12:54:17][INFO][lindm] 
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [-0. -0. -0.  1.]]


array([[-5, -5, -6, -2],
       [-4, -5, -3, -3],
       [-3, -2, -5, -2],
       [-4, -3, -6, -5]])

## Ejercicios

* Ejercicio 1

In [41]:
A = [[2, -3], [-1, 1]]
inv_matrix(A)
np.invert(A)



[01-29 12:54:17][INFO][lindm] Intercambiando filas 0 y 1.
[01-29 12:54:17][INFO][lindm] 
[[ 1. -1.]
 [ 0. -1.]]
[01-29 12:54:17][INFO][lindm] 
[[ 1.  0.]
 [-0.  1.]]


array([[-3,  2],
       [ 0, -2]])

* Ejercicio 2

In [42]:
A = [
    [4, 0, 0, 5],
    [1, 0, 4, 0],
    [3, 4, 1, 3],
    [1, 3, 3, 0],
]
inv_matrix(A)

[01-29 12:54:17][INFO][lindm] Intercambiando filas 0 y 1.
[01-29 12:54:17][INFO][lindm] 
[[  1.   0.   4.   0.]
 [  0.   0. -16.   5.]
 [  0.   4. -11.   3.]
 [  0.   3.  -1.   0.]]
[01-29 12:54:17][INFO][lindm] Intercambiando filas 1 y 3.
[01-29 12:54:17][INFO][lindm] 
[[  1.           0.           4.           0.        ]
 [  0.           1.          -0.33333333   0.        ]
 [  0.           0.          -9.66666667   3.        ]
 [  0.           0.         -16.           5.        ]]
[01-29 12:54:17][INFO][lindm] 
[[ 1.          0.          0.          1.24137931]
 [ 0.          1.          0.         -0.10344828]
 [-0.         -0.          1.         -0.31034483]
 [ 0.          0.          0.          0.03448276]]
[01-29 12:54:17][INFO][lindm] 
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [-0. -0.  1.  0.]
 [ 0.  0.  0.  1.]]


array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [-0., -0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

* Ejercicio 3

In [43]:
A = [
    [0, 0, 0, 0, 0, 0, 1, -1],
    [0, 1, -1, 1, 0, -1, 0, 1],
    [-1, -1, 0, 0, 2, 1, 0, 0],
    [-1, -1, -1, 1, 2, 0, 0, 1],
    [-1, 1, 1, 0, -1, -1, 0, 2],
    [0, 1, 0, 0, -1, -1, 0, 0],
    [1, -1, -1, 1, 2, 1, 0, 2],
    [2, 0, 0, 0, 0, 1, 2, 0],
]
inv_matrix(A)

[01-29 12:54:17][INFO][lindm] Intercambiando filas 0 y 2.
[01-29 12:54:17][INFO][lindm] 
[[ 1.  1. -0. -0. -2. -1. -0. -0.]
 [ 0.  1. -1.  1.  0. -1.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.]
 [ 0.  0. -1.  1.  0. -1.  0.  1.]
 [ 0.  2.  1.  0. -3. -2.  0.  2.]
 [ 0.  1.  0.  0. -1. -1.  0.  0.]
 [ 0. -2. -1.  1.  4.  2.  0.  2.]
 [ 0. -2.  0.  0.  4.  3.  2.  0.]]
[01-29 12:54:17][INFO][lindm] 
[[ 1.  0.  1. -1. -2.  0. -0. -1.]
 [ 0.  1. -1.  1.  0. -1.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.]
 [ 0.  0. -1.  1.  0. -1.  0.  1.]
 [ 0.  0.  3. -2. -3.  0.  0.  0.]
 [ 0.  0.  1. -1. -1.  0.  0. -1.]
 [ 0.  0. -3.  3.  4.  0.  0.  4.]
 [ 0.  0. -2.  2.  4.  1.  2.  2.]]
[01-29 12:54:17][INFO][lindm] Intercambiando filas 2 y 3.
[01-29 12:54:17][INFO][lindm] 
[[ 1.  0.  0.  0. -2. -1.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [-0. -0.  1. -1. -0.  1. -0. -1.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.]
 [ 0.  0.  0.  1. -3. -3.  0.  3.]
 [ 0.  0.  0.  0. -1. -1.  0.  0.]
 [ 0.  0.  0.  0.  

[01-29 12:54:17][INFO][lindm] Intercambiando filas 4 y 5.
[01-29 12:54:17][INFO][lindm] 
[[ 1.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [-0. -0.  1.  0.  0.  1.  0.  2.]
 [ 0.  0.  0.  1.  0.  0.  0.  3.]
 [-0. -0. -0. -0.  1.  1. -0. -0.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.]
 [ 0.  0.  0.  0.  0. -1.  0.  1.]
 [ 0.  0.  0.  0.  0. -1.  2.  0.]]
[01-29 12:54:17][INFO][lindm] Intercambiando filas 5 y 6.
[01-29 12:54:17][INFO][lindm] 
[[ 1.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [-0. -0.  1.  0.  0.  0.  0.  3.]
 [ 0.  0.  0.  1.  0.  0.  0.  3.]
 [-0. -0. -0. -0.  1.  0.  0.  1.]
 [-0. -0. -0. -0. -0.  1. -0. -1.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.]
 [ 0.  0.  0.  0.  0.  0.  2. -1.]]
[01-29 12:54:17][INFO][lindm] 
[[ 1.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.]
 [-0. -0.  1.  0.  0.  0.  0.  3.]
 [ 0.  0.  0.  1.  0.  0.  0.  3.]
 [-0. -0. -0. -0.  1.  0.  0.  1.]
 [-0. -0. -0. -0. -0.  1.  0. -1.]
 [ 0.  0.  0.  0.  

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-0., -0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [-0., -0., -0., -0.,  1.,  0.,  0.,  0.],
       [-0., -0., -0., -0., -0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

* Ejercicio 4

In [44]:
A = [
    [1, 0, 0, 0, -1, 0, 0, -1, 1, -1],
    [1, 1, 0, -1, -1, 1, 0, 0, 1, -1],
    [-1, 0, -1, 0, 0, 0, -1, 1, 0, 0],
    [0, 0, -1, 0, -1, -1, 1, 0, 1, 0],
    [-1, 0, 0, -1, 1, 1, 1, 1, 0, -1],
    [1, 0, 0, 1, -1, -1, -1, 1, -1, 0],
    [1, 1, 1, 0, 1, 0, -1, -1, -1, 1],
    [1, 1, 1, 1, 0, 0, 1, 1, 0, 0],
    [1, 1, 1, 1, 1, 0, -1, -1, 0, 0],
    [0, 0, -1, -1, -1, 0, 1, 1, 1, -1],
]
inv_matrix(A)

[01-29 12:54:17][INFO][lindm] 
[[ 1.  0.  0.  0. -1.  0.  0. -1.  1. -1.]
 [ 0.  1.  0. -1.  0.  1.  0.  1.  0.  0.]
 [ 0.  0. -1.  0. -1.  0. -1.  0.  1. -1.]
 [ 0.  0. -1.  0. -1. -1.  1.  0.  1.  0.]
 [ 0.  0.  0. -1.  0.  1.  1.  0.  1. -2.]
 [ 0.  0.  0.  1.  0. -1. -1.  2. -2.  1.]
 [ 0.  1.  1.  0.  2.  0. -1.  0. -2.  2.]
 [ 0.  1.  1.  1.  1.  0.  1.  2. -1.  1.]
 [ 0.  1.  1.  1.  2.  0. -1.  0. -1.  1.]
 [ 0.  0. -1. -1. -1.  0.  1.  1.  1. -1.]]
[01-29 12:54:17][INFO][lindm] 
[[ 1.  0.  0.  0. -1.  0.  0. -1.  1. -1.]
 [ 0.  1.  0. -1.  0.  1.  0.  1.  0.  0.]
 [ 0.  0. -1.  0. -1.  0. -1.  0.  1. -1.]
 [ 0.  0. -1.  0. -1. -1.  1.  0.  1.  0.]
 [ 0.  0.  0. -1.  0.  1.  1.  0.  1. -2.]
 [ 0.  0.  0.  1.  0. -1. -1.  2. -2.  1.]
 [ 0.  0.  1.  1.  2. -1. -1. -1. -2.  2.]
 [ 0.  0.  1.  2.  1. -1.  1.  1. -1.  1.]
 [ 0.  0.  1.  2.  2. -1. -1. -1. -1.  1.]
 [ 0.  0. -1. -1. -1.  0.  1.  1.  1. -1.]]
[01-29 12:54:17][INFO][lindm] 
[[ 1.  0.  0.  0. -1.  0.  0. -1.  1. -1.]
 [

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-0., -0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-0., -0., -0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [-0., -0., -0., -0., -0.,  1.,  0.,  0.,  0.,  0.],
       [-0., -0., -0., -0., -0., -0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])